/**
 * Public BOM WMTS layer registry.
 *
 * Kept in a data-only module so runtime code, deterministic tests, and
 * upstream validation all consume the same timing configuration.
 */

export const BOM_LAYER_GROUPS = [
  'Rain / observed',
  'Rain / forecast',
  'Wind',
  'Waves',
  'Temperature',
  'Humidity & UV',
  'Significant weather',
];

// Top-left corners use EPSG:3857 coordinates. These values and dimensions are
// part of the runtime tile-coordinate conversion and are checked against BOM's
// current capabilities by scripts/check-bom-upstream.mjs.
export const BOM_TILE_MATRIX_SETS = {
  GoogleMapsCompatible_BoM: [
    { z: 0, tlx: 11584952, tly: 34168990.685578, w: 1, h: 1 },
    { z: 1, tlx: 11584952, tly: 14131482.342789, w: 1, h: 1 },
    { z: 2, tlx: 11584952, tly: 4112728.171395, w: 1, h: 1 },
    { z: 3, tlx: 11584952, tly: 4112728.171395, w: 2, h: 2 },
    { z: 4, tlx: 11584952, tly: 1608039.628546, w: 3, h: 3 },
    { z: 5, tlx: 11584952, tly: 355695.357122, w: 6, h: 5 },
    { z: 6, tlx: 11584952, tly: -270476.778591, w: 11, h: 9 },
    { z: 7, tlx: 11584952, tly: -583562.846447, w: 22, h: 17 },
    { z: 8, tlx: 11584952, tly: -740105.880375, w: 43, h: 33 },
  ],
  GoogleMapsCompatible_BoM_ADFD: [
    { z: 0, tlx: 12462758.1832, tly: 34449560.527478, w: 1, h: 1 },
    { z: 1, tlx: 12462758.1832, tly: 14412052.184689, w: 1, h: 1 },
    { z: 2, tlx: 12462758.1832, tly: 4393298.013295, w: 1, h: 1 },
    { z: 3, tlx: 12462758.1832, tly: -616079.072403, w: 1, h: 1 },
    { z: 4, tlx: 12462758.1832, tly: -616079.072403, w: 2, h: 2 },
    { z: 5, tlx: 12462758.1832, tly: -616079.072403, w: 4, h: 4 },
    { z: 6, tlx: 12462758.1832, tly: -616079.072403, w: 8, h: 8 },
    { z: 7, tlx: 12462758.1832, tly: -616079.072403, w: 16, h: 16 },
    { z: 8, tlx: 12462758.1832, tly: -772622.106331, w: 31, h: 31 },
  ],
};

export const BOM_LAYERS = {
  'rain_rate': {
    id: 'atm_surf_air_precip_rate_1hr_total_mm_h',
    name: 'Rain Rate',
    category: 'Rain / observed',
    unit: 'mm/h',
    tileMatrixSet: 'GoogleMapsCompatible_BoM',
    legendType: 'rainRadar',
    timeMode: 'past',
    fallbackStepMinutes: 5,
    fallbackLagMinutes: 5,
    initialFrame: 'latest',
  },
  'accumulation_1hr': {
    id: 'atm_surf_air_precip_accumulation_1hr_total_mm',
    name: 'Estimated Rain 1hr',
    category: 'Rain / observed',
    unit: 'mm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM',
    legendType: 'numerical',
    timeMode: 'past',
    fallbackStepMinutes: 5,
    fallbackLagMinutes: 5,
    initialFrame: 'latest',
  },
  'accumulation_24hr': {
    id: 'atm_surf_air_precip_accumulation_24hr_total_mm',
    name: 'Accumulated Rain 24hr',
    category: 'Rain / observed',
    unit: 'mm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM',
    legendType: 'numerical',
    timeMode: 'past',
    fallbackStepMinutes: 1440,
    fallbackLagMinutes: 0,
    fallbackAnchorHourUtc: 9,
    fallbackMaxFrames: 7,
    initialFrame: 'latest',
  },
  'reflectivity': {
    id: 'atm_surf_air_precip_reflectivity_dbz',
    name: 'Rain Reflectivity',
    category: 'Rain / observed',
    unit: 'dBZ',
    tileMatrixSet: 'GoogleMapsCompatible_BoM',
    legendType: 'rainRadar',
    timeMode: 'past',
    fallbackStepMinutes: 5,
    fallbackLagMinutes: 10,
    initialFrame: 'latest',
  },
  'forecast_rain_50pct_3hr': {
    id: 'atm_surf_air_precip_exceeding_50percentchance_total_mm_3hourly',
    name: 'Forecast Rain 50% 3hr',
    category: 'Rain / forecast',
    unit: 'mm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'forecast_rain_50pct_daily': {
    id: 'atm_surf_air_precip_exceeding_50percentchance_total_mm_daily',
    name: 'Forecast Rain 50% Daily',
    category: 'Rain / forecast',
    unit: 'mm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 1440,
    fallbackLagMinutes: 0,
    fallbackAnchorHourUtc: 15,
    fallbackMaxFrames: 7,
    initialFrame: 'first',
  },
  'forecast_rain_25pct_3hr': {
    id: 'atm_surf_air_precip_exceeding_25percentchance_total_mm_3hourly',
    name: 'Forecast Rain 25% 3hr',
    category: 'Rain / forecast',
    unit: 'mm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'forecast_rain_25pct_daily': {
    id: 'atm_surf_air_precip_exceeding_25percentchance_total_mm_daily',
    name: 'Forecast Rain 25% Daily',
    category: 'Rain / forecast',
    unit: 'mm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 1440,
    fallbackLagMinutes: 0,
    fallbackAnchorHourUtc: 15,
    fallbackMaxFrames: 7,
    initialFrame: 'first',
  },
  'forecast_rain_10pct_3hr': {
    id: 'atm_surf_air_precip_exceeding_10percentchance_total_mm_3hourly',
    name: 'Forecast Rain 10% 3hr',
    category: 'Rain / forecast',
    unit: 'mm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'forecast_rain_10pct_daily': {
    id: 'atm_surf_air_precip_exceeding_10percentchance_total_mm_daily',
    name: 'Forecast Rain 10% Daily',
    category: 'Rain / forecast',
    unit: 'mm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 1440,
    fallbackLagMinutes: 0,
    fallbackAnchorHourUtc: 15,
    fallbackMaxFrames: 7,
    initialFrame: 'first',
  },
  'forecast_rain_chance_3hr': {
    id: 'atm_surf_air_precip_any_probability_percent_3hourly',
    name: 'Chance of Rain 3hr',
    category: 'Rain / forecast',
    unit: '%',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'forecast_rain_chance_daily': {
    id: 'atm_surf_air_precip_any_probability_percent_daily',
    name: 'Chance of Rain Daily',
    category: 'Rain / forecast',
    unit: '%',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 1440,
    fallbackLagMinutes: 0,
    fallbackAnchorHourUtc: 15,
    fallbackMaxFrames: 7,
    initialFrame: 'first',
  },
  'wind_speed_kmh': {
    id: 'atm_surf_air_wind_speed_10m_avg_kmh_3hourly',
    name: 'Wind Speed',
    category: 'Wind',
    unit: 'km/h',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'wind_speed_kt': {
    id: 'atm_surf_air_wind_speed_10m_avg_kt_3hourly',
    name: 'Wind Speed',
    category: 'Wind',
    unit: 'kt',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'wind_direction': {
    id: 'atm_surf_air_wind_dirn_10m_deg_t_3hourly',
    name: 'Wind Direction',
    category: 'Wind',
    unit: 'deg',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'wave_total_height': {
    id: 'ocn_surf_water_wave_total_height_m_3hourly',
    name: 'Total Wave Height',
    category: 'Waves',
    unit: 'm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'swell_1_height': {
    id: 'ocn_surf_water_swell_1st_height_m_3hourly',
    name: 'Swell 1 Height',
    category: 'Waves',
    unit: 'm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'swell_1_direction': {
    id: 'ocn_surf_water_swell_1st_dirn_deg_t_3hourly',
    name: 'Swell 1 Direction',
    category: 'Waves',
    unit: 'deg',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'swell_2_height': {
    id: 'ocn_surf_water_swell_2nd_height_m_3hourly',
    name: 'Swell 2 Height',
    category: 'Waves',
    unit: 'm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'swell_2_direction': {
    id: 'ocn_surf_water_swell_2nd_dirn_deg_t_3hourly',
    name: 'Swell 2 Direction',
    category: 'Waves',
    unit: 'deg',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'wind_wave_height': {
    id: 'ocn_surf_water_wave_height_wind_m_3hourly',
    name: 'Wind Wave Height',
    category: 'Waves',
    unit: 'm',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'air_temperature': {
    id: 'atm_surf_air_temp_cel_3hourly',
    name: 'Air Temperature',
    category: 'Temperature',
    unit: '°C',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'feels_like': {
    id: 'atm_surf_air_temp_apparent_cel_3hourly',
    name: 'Feels Like',
    category: 'Temperature',
    unit: '°C',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'temperature_max_daily': {
    id: 'atm_surf_air_temp_max_cel_daily',
    name: 'Daytime Maximum',
    category: 'Temperature',
    unit: '°C',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 1440,
    fallbackLagMinutes: 0,
    fallbackAnchorHourUtc: 0,
    fallbackMaxFrames: 7,
    initialFrame: 'first',
  },
  'temperature_min_daily': {
    id: 'atm_surf_air_temp_min_cel_daily',
    name: 'Overnight Minimum',
    category: 'Temperature',
    unit: '°C',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 1440,
    fallbackLagMinutes: 0,
    fallbackAnchorHourUtc: 12,
    fallbackMaxFrames: 7,
    initialFrame: 'first',
  },
  'heatwave_severity': {
    id: 'atm_surf_air_temp_heatwave_severity_code_daily',
    name: 'Heatwave Severity',
    category: 'Temperature',
    unit: 'level',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 1440,
    fallbackLagMinutes: 0,
    fallbackAnchorHourUtc: 0,
    fallbackMaxFrames: 7,
    initialFrame: 'first',
  },
  'relative_humidity': {
    id: 'atm_surf_air_hum_relative_percent_3hourly',
    name: 'Relative Humidity',
    category: 'Humidity & UV',
    unit: '%',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'dew_point': {
    id: 'atm_surf_air_temp_dew_pt_cel_3hourly',
    name: 'Dew Point',
    category: 'Humidity & UV',
    unit: '°C',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'uv_index': {
    id: 'atm_surf_air_radiation_uv_clear_sky_code_3hourly',
    name: 'UV Index',
    category: 'Humidity & UV',
    unit: 'index',
    tileMatrixSet: 'GoogleMapsCompatible_BoM',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'uv_max_daily': {
    id: 'atm_surf_air_radiation_uv_clear_sky_max_code_daily',
    name: 'Max UV Daily',
    category: 'Humidity & UV',
    unit: 'index',
    tileMatrixSet: 'GoogleMapsCompatible_BoM',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 1440,
    fallbackLagMinutes: 0,
    fallbackLeadMinutes: 1440,
    fallbackAnchorHourUtc: 0,
    fallbackMaxFrames: 4,
    initialFrame: 'first',
  },
  'thunderstorms': {
    id: 'atm_surf_air_weather_icon_thunderstorm_code_3hourly',
    name: 'Thunderstorms',
    category: 'Significant weather',
    unit: 'icon',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'snow': {
    id: 'atm_surf_air_weather_icon_snow_code_3hourly',
    name: 'Snow',
    category: 'Significant weather',
    unit: 'icon',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'fog': {
    id: 'atm_surf_air_weather_icon_fog_code_3hourly',
    name: 'Fog',
    category: 'Significant weather',
    unit: 'icon',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
  'frost': {
    id: 'atm_surf_air_weather_icon_frost_code_3hourly',
    name: 'Frost',
    category: 'Significant weather',
    unit: 'icon',
    tileMatrixSet: 'GoogleMapsCompatible_BoM_ADFD',
    legendType: 'numerical',
    timeMode: 'forecast',
    fallbackStepMinutes: 180,
    fallbackLagMinutes: 0,
    initialFrame: 'first',
  },
};
